### PR TITLE
Add directives to the API Reference

### PR DESCRIPTION
**Pull request by santisoler**
#### Summary

List directives in the API Reference under their own "Directives" category.

#### PR Checklist
* [ ] If this is a work in progress PR, set as a Draft PR
* [ ] Linted my code according to the [style guides](https://docs.simpeg.xyz/content/getting_started/contributing/code-style.html).
* [ ] Added [tests](https://docs.simpeg.xyz/content/getting_started/practices.html#testing) to verify changes to the code.
* [ ] Added necessary documentation to any new functions/classes following the
      expect [style](https://docs.simpeg.xyz/content/getting_started/practices.html#documentation).
* [ ] Marked as ready for review (if this is was a draft PR), and converted
      to a Pull Request
* [ ] Tagged ``@simpeg/simpeg-developers`` when ready for review.

#### What does this implement/fix?

Fixes 1396

### CODE REVIEW

**Comment by santisoler** [comment]
Looking nice!

image

**Comment by santisoler** [comment]
I would appreciate if someone would like to improve/add some words to the docs in the `directives/__init__.py`. We can do it here, or I can just merge this PR and then we can continue working on them in a separate one.

**Comment by jcapriot** [comment]
Looks, good. My only request is to move the Base Directives to the end of the list, since they are never directly used.

**Review by jcapriot — APPROVED** [review]
Looks good to get them into the API

**Pull request merged**
