### PR TITLE
Fixing NSEM codacy errors

### PR DESCRIPTION
**Pull request by grosenkj**
Address some of the codacy issues from https://www.codacy.com/app/lindseyheagy/simpeg/pullRequest?prid=363079

(Note: none of the issues in `Utils` have been address, will be in next NSEM updates)

### CODE REVIEW

**Comment by lheagy** [comment]
thanks for doing this @grosenkj!

**Comment by grosenkj** [comment]
No, worries. Didn't fix any of the `Utils` issues since those will be address in near future work.

**Comment by grosenkj** [comment]
@lheagy, this can be closed?

**Comment by grosenkj** [comment]
It is already, it hadn't updated in my browser.

**Pull request merged**
