### PR TITLE
add test to ensure examples are up to date

### PR DESCRIPTION
**Pull request by lheagy**

### CODE REVIEW

**Comment by lheagy** [comment]
not entirely sure why the pr fails... I will try to write some more useful output to the test.

**Comment by lheagy** [comment]
now it passes! @rowanc1 : can you take a quick look when you get a chance?

**Comment by rowanc1** [comment]
No idea. Seems to work now though?

**Comment by lheagy** [comment]
in the first pass through, I used relpath instead of abspath, and I think it was a bit touchy. abspath seems to be better behaved

**Pull request merged**
