### PR TITLE
Ditch deprecated functions in utils.model_builder

### PR DESCRIPTION
**Pull request by domfournier**
Addresses name change for functions in `utils.model_builder`.
Update tutorials, examples and tests that were using the deprecated functions.

Related to issue #1265

### CODE REVIEW

**Review by santisoler — APPROVED** [review]
Thanks @domfournier for this! I've started working on ditching deprecated function in https://github.com/simpeg/simpeg/tree/ditch-deprecated (I'll open a PR shortly). I haven't worked on these functions yet, so these changes are greatly appreciated.

I just pushed a few commits to this branch to remove the deprecated functions, and also update some bits that were still using the deprecated functions. Hopefully CI won't fail. In case it does fail, feel free to push further changes.

**Comment by domfournier** [comment]
Great @santisoler , getting cleaner. I have noticed some random failures of the dask.dc test though. Created issue #1315 to investigate. I would suggest we just re-fire the test here until it passes.

**Comment by santisoler** [comment]
Thanks for opening that issue. If the test involves some random numbers, the failing might be related to https://github.com/simpeg/simpeg/issues/1289

**Comment by santisoler** [comment]
Now tests passed. I'm merging this!

**Comment by Hghadjari** [comment]
mesh = refine_tree_xyz(
/home/hossein/anaconda3/envs/simpeg1/lib/python3.12/site-packages/scipy/interpolate/_interpolate.py:710: RuntimeWarning: invalid value encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
Traceback (most recent call last):
  File "/home/hossein/simpeg/plot_fwd_2_dcr2d.py", line 126, in <module>
    mesh = refine_tree_xyz(
           ^^^^^^^^^^^^^^^^
  File "/home/hossein/anaconda3/envs/simpeg1/lib/python3.12/site-packages/discretize/utils/mesh_utils.py", line 837, in refine_tree_xyz
    r, ind = tree.query(newLoc)
             ^^^^^^^^^^^^^^^^^^
  File "_ckdtree.pyx", line 795, in scipy.spatial._ckdtree.cKDTree.query
ValueError: 'x' must be finite, check for nan or inf values

**Pull request merged**
