### PR TITLE
Remove default from the private `_get` method in properties.

### PR DESCRIPTION
**Pull request by rowanc1**
The release notes are here:
https://github.com/3ptscience/properties/releases/tag/v0.2.3

See #497

### CODE REVIEW

**Comment by lheagy** [comment]
maybe in the future as updates are coming into `properties` we can post a message in the simpeg slack channel?

**Comment by fwkoch** [comment]
@lheagy - I can definitely post in the simpeg slack channel when updates to `properties` are coming. I'll plan to put big changes on a beta `pip` release for a few days, so migrating may be a bit smoother.

Sorry about that!

**Comment by fwkoch** [comment]
Release notes for yesterday's changes are here: https://github.com/3ptscience/properties/releases/tag/v0.2.3

**Comment by rowanc1** [comment]
Thanks @fwkoch!

**Pull request merged**
