### PR TITLE
Issue-1037

### PR DESCRIPTION
**Pull request by domfournier**
Addresses issue #1037 
- Standardize sparse inversion to cell_weights normalized by volume.
- Add model_type property to base.simulation to handle sensitivity weights update.
- Minor variables cleanup

### CODE REVIEW

**Comment by micmitch** [comment]
This pull request fixes problems I was having when I tried to use @xiaolongw1223 new depth weighting functionality with the existing sparse regularization. Due to an inconsistency with volume normalization I was getting structure in the recovered model at each depth interface where cell sizes changed in my octree mesh.

image

L2 inversion using depth weighting on main SimPEG branch

image

L2 inversion using depth weighting on this branch.

This result is very comparable to the same inversion done with sensitivity weighting.

image

**Comment by xiaolongw1223** [comment]
Results look pretty! @micmitch

**Comment by domfournier** [comment]
> Results look pretty! @micmitch

Yea what's that colormap anyway? Me licky.

**Comment by micmitch** [comment]
Thanks for your help @xiaolongw1223  and @domfournier !

**Comment by micmitch** [comment]
> > Results look pretty! @micmitch
> 
> Yea what's that colormap anyway? Me licky.

That's a custom colormap that I made. Kind of meant to simulate a diverging version of Viridis. My supervisor is not a big fan of Viridis. Hopefully this is a good middle ground between Viridis and Seismic. :)

**Pull request merged**
