### PR TITLE
Add conda-forge badge

### PR DESCRIPTION
**Pull request by prisae**

### CODE REVIEW

**Review by thast — APPROVED** [review]
that looks good! Thanks @prisae , great idea!

**Comment by adjafari** [comment]
I had many difficulties to install simpeg on ubuntu 20. Can somebody know ho do?

**Comment by prisae** [comment]
How do you use Python? With conda it should be straight forward. I am on Ubuntu 20, and it is a matter of seconds to install it.

**Comment by thast** [comment]
Hi @adjafari, welcome.
For discussions and help, we have dedicated platforms. Please feel free to reach us on them whenever you are facing challenges:
1) a slack group that you can join following this link: http://slack.simpeg.xyz/
2) a discourse, https://simpeg.discourse.group/

This will make this discussion more visible; thus, more people can help, and people experiencing similar issues will see it.

Thank you for your interest.

**Pull request merged**
