### PR TITLE
Describe merge process of Pull Requests in docs

### LINKED ISSUE #1369: MAINT: use "Squash and Merge" for merging PRs?
A few months ago we started a conversation around the usage of the ["Squash and Merge"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits) strategy for merging Pull Requests to `main`, as opposed to using the traditional ["Merge"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#merge-your-commits). I think it would be nice to bring back this topic and decide if we would like to use it as the main method to merge PRs in SimPEG or if we would like to choose another solution.

## The Motivation

The motivation behind this idea is to have a cleaner and more useful commit history in `main`.

Currently in SimPEG all changes that are incorporated to `main` are made through a Pull Request, over which we enforce some best practices: 
* Each Pull Request should be concise and should solve a single problem or implement a single feature.
* Pull Requests must have comprehensive descriptions about what problem is solving or feature is implementing and how.
* Pull Requests will be merged only if they pass all tests, include new tests for new bits of code, and the documentation builds properly.
* Pull Requests should be peer-reviewed before merging them.

In abstract, this means that every new change in SimPEG is tied to a Pull Request, and those changes had been thoroughly tested and reviewed. Therefore we can conceive the `main` branch as a sequence of these states.

Nonetheless, the [commit history of the `main` branch](https://github.com/simpeg/simpeg/commits/main/) doesn't fully reflect that mental picture. By using the Merge strategy we are including every _intermediate_ commit in every Pull Request, populating the commit history with non-descriptive commits. 
For example, we can find commits like https://github.com/simpeg/simpeg/commit/10add2d334889df3d255b04275a2afa90b61a9c6, which message is `remove print statement`: it lacks the context for this change, the reasons why that print statement was removed, and which Pull Request that commit was part of.

## The benefits of Squash and Merge

Squash and Merge will _squash_ all commits in the branch of the PR and create a single commit in `main` that groups together every change in that PR. This introduces some benefits:

* Each commit in `main` will be tied to a particular PR, providing more context on why those changes have been applied.
* Maintainers have the ability to double check and improve the commit message that will be included in `main`. This ease the load of contributors for writing good commit messages (good commit messages are welcomed, but if we can ease that load from new contributors, that's great).
* Since all PRs must pass tests and documentation should build properly before they are merged, with Squash and Merge we can ensure that at any point in `main` the code is tested and docs are building.
* Since each commit is tied to a single PR, reverting the changes of a whole PR can easily be done with `git revert <commit-hash>`. This can be useful in case we find something is critically wrong after we merged it.

As an example of a PR that was merge using Squash and Merge, check out https://github.com/simpeg/simpeg/commit/c6d05c30ea7c574db4eedf979ad51df86ce60eaf

If you want to take a look at how a commit history using Squash and Merge looks like, checkout [harmonica's](https://github.com/fatiando/harmonica/commits/main/). Other libraries in the scientific ecosystem are using it, like [scikit-learn](https://github.com/scikit-learn/scikit-learn/issues/17304#issuecomment-636004140), or [scipy](https://github.com/scipy/scipy/pull/19807#pullrequestreview-1806154959).

## The cons of Squash and Merge

The biggest downside of Squash and Merge is that we loose information in the process. Since a single commit is created on `main` for the whole PR, we loose the information contained in the intermediate ones, and therefore loosingsome of the inner details of how we arrived to those changes.

The other con of Squash and Merge is that the commits in `main` will be more lengthy, since they'd contain new code + tests + docs.

## Personal opinion

I'm in favor of Squash and Merge. I've been using it in most of the projects I maintain and I'm super happy with it. Loosing intermediate information about the process of each PR is true, but we can always go back to the Pull Request and see the commits (even after deleting the branch, check out this for example: https://github.com/fatiando/harmonica/pull/429).

I think that having a cleaner commit history in `main` has way more value than being able to read every intermediate commit.

## How to implement this if we decide to go forward

In case we would like to make Squash and Merge the default way of merging PRs, we can add a new rule to the `main` branch protection, allowing only the Squash and Merge method.

This won't have any impact on the contributor's experience while opening PRs. We'll still encourage good commit messages and nice PR descriptions. Maintainers should be in charge of making sure that those descriptions are accurate and comprehensive before merging the PR, and edit the commit message while squash-and-merging.

**Edit 2024-03-07:**

- [ ] Edit Contributor Guide adding a description of the merge process using Squash and Merge

### PR DESCRIPTION
**Pull request by santisoler**
#### Summary

Add a description about how the merge process of Pull Requests will be done, detailing that the Squash and Merge will be used.

#### PR Checklist
* [ ] If this is a work in progress PR, set as a Draft PR
* [ ] Linted my code according to the [style guides](https://docs.simpeg.xyz/content/getting_started/contributing/code-style.html).
* [ ] Added [tests](https://docs.simpeg.xyz/content/getting_started/practices.html#testing) to verify changes to the code.
* [ ] Added necessary documentation to any new functions/classes following the
      expect [style](https://docs.simpeg.xyz/content/getting_started/practices.html#documentation).
* [ ] Marked as ready for review (if this is was a draft PR), and converted
      to a Pull Request
* [ ] Tagged ``@simpeg/simpeg-developers`` when ready for review.

#### Reference issue

Fixes #1369

### CODE REVIEW

**Comment by santisoler** [comment]
@lheagy Would you like to take a look at this?

**Review by jcapriot — APPROVED** [review]
Looks good.

A side note. Since it default fills with the entire message of the PR, we'll need to take out the boilerplate stuff that is commented out markdown when we do this.

**Comment by santisoler** [comment]
> Looks good.
> 
> A side note. Since it default fills with the entire message of the PR, we'll need to take out the boilerplate stuff that is commented out markdown when we do this.
`
Yes! I usually leave the summary + any other important information. But basically trying to keep it under ~10 lines. Not a strict limit though.

**Review by lheagy — APPROVED** [review]
Thanks so much for this @santisoler! Looks good to me

**Pull request merged**
