### PR TITLE
Update plot_inv_1a_gravity_anomaly.py

### PR DESCRIPTION
**Pull request by RichardScottOZ**
Minor edits

### CODE REVIEW

**Comment by RichardScottOZ** [comment]
Questions to add: it says you can create a starting model and/or a reference model....then proceeds to ignore the reference model for a simple background starting model. Should say what it is and why you use one?

**Review by thast — APPROVED** [review]
That looks good! Thanks again! Regarding your question about the reference model, I believed you got an answer on Slack (for the record here: if no reference model is provided when defining the regularization, the starting model is used as the reference model).

**Comment by RichardScottOZ** [comment]
Yes, the important part bit being you can access with regularization.ref Dom said - and hence set values where you want to?

**Comment by thast** [comment]
@RichardScottOZ:
In detail, you can set a reference model that you have previously built (let's call it `reference_model`) when defining the regularization. 
- For example `reg = regularization.Tikhonov(mesh=mesh, mref=reference_model)` 
- This is similar to doing what you just said: `reg.mref=reference_model`
- In addition, you can also act on adding bounds constraints. the `ProjectedGNCG` accepts arrays as `lower` and `upper` bounds. For example, you can define `opt=optimization.ProjectedGNCG(maxiter=20, lower=reference_model-1, upper=reference_model+1)`

**Comment by RichardScottOZ** [comment]
Thanks very much forvthe detail.

**Comment by RichardScottOZ** [comment]
So for lower and upper you can vary the array. Say I want a cover sequence of units to stay the same, set the lower=upper at those indices?

**Comment by thast** [comment]
yes that works.

**Comment by RichardScottOZ** [comment]
Thanks.

**Pull request merged**
