### PR TITLE
Em/dev

### PR DESCRIPTION
**Pull request by rowanc1**

### CODE REVIEW

**Comment by lheagy** [comment]
@fourndo , @sgkang: can you guys take a look at this pr? There is some white-space fixing, this is minor... The major item is the removal of the PropMap and use of Properties. These changes touch the EM, PF, Static codes, including IP, so your thoughts would be much appreciated! A more detailed overview of the changes is in #471.

**Comment by lheagy** [comment]
- [ ] can we throw an error if you try to set curModel? (now `model` needs to be set).

**Comment by rowanc1** [comment]
Good point. Add a `@property` stub that just raises an `Exception`?

**Comment by rowanc1** [comment]
@sgkang did you merge all of the em/dev branch back into itself? What happened on the last commit? there are 108 changes?

**Comment by sgkang** [comment]
I am pretty sure that is pulling the latest em/dev. I was way behind when I comitted changes, then pulled.

**Comment by lheagy** [comment]
I will reopen a pull request from https://github.com/simpeg/simpeg/pull/473/commits/0c6e9e3d1922d6dc6a94994631ad990d1c340e7f

**Pull request closed without merging**
