### PR TITLE
Pass `rtol` to SciPy solvers for SciPy>=1.12

### LINKED ISSUE #1516: BUG: SciPy 1.14 removed the `tol` argument of `scipy.sparse.linalg.***`
### Describe the issue:

SciPy 1.14 removed the `tol` argument of `scipy.sparse.linalg.{bcg,bicstab,cg,cgs,gcrotmk, mres,lgmres,minres,qmr,tfqmr}` in favour of `rtol`. Furthermore, the default value of `atol` for these functions has changed to `0.0`. (It was deprecated in SciPy 1.12.)

This will need some changes in the code base.

### Reproducible code example:

```python
Any code example that uses a scipy.sparse.linalg-solver.
```

### Error message:

```shell
/simpeg/simpeg/optimization.py:1072: UserWarning: tol is not a valid keyword for cg and will be ignored
  Hinv = SolverICG(
```
```


### Runtime information:

SciPy >= 1.14

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by prisae**
#### Summary

Pass `rtol` or `tol` to SciPy solvers depending on the available version of SciPy: for `scipy>=1.12` use `rtol`, otherwise use `tol`. SciPy 1.12 changed `tol` to `rtol` for `scipy.sparse.linalg...`, and removed `tol` in SciPy 1.14.

See #1516

Just a simple attempt, maybe you have other ideas, feel free to close this one in favour of another solution!

#### PR Checklist
* [ ] Linted my code according to the [style guides](https://docs.simpeg.xyz/content/getting_started/contributing/code-style.html).
* [ ] Added [tests](https://docs.simpeg.xyz/content/getting_started/practices.html#testing) to verify changes to the code.
* [ ] Added necessary documentation to any new functions/classes following the
      expect [style](https://docs.simpeg.xyz/content/getting_started/practices.html#documentation).
* [x] Tagged ``@simpeg/simpeg-developers`` when ready for review.

@simpeg/simpeg-developers - ready for review

#### Reference issue
Closes #1516

### CODE REVIEW

**Comment by santisoler** [comment]
Thanks @prisae for opening this. I think you approach should work. I just pushed a few changes, feel free to comment on those or just push corrections to them:

1. I used `packaging.version.parse()` to check if the installed version of scipy is greater or equal to 1.12. I think this is a more robust check than comparing only to the values for the minor release.
2. I applied some changes to the code style: uppercase the global variable for the scipy version flag, define the dictionary `inp` only once and use a predefined variable for the tolerance key.

Let me know what do you think!

cc @jcapriot. Would you agree on adding `packaging` as a required dependency?

**Comment by prisae** [comment]
Not sure if it is worth to add a dependency for an issue that will go away soon again (as soon as the minimum SciPy version is. But no hard feelings in this respect, either is fine!

**Comment by jcapriot** [comment]
I honestly wouldn’t worry much about the formatting or details on this, as it will all get removed in #1511 as these will rely on the pymatsolver versions.

**Comment by prisae** [comment]
Awesome! (This speaks against adding an additional dependency, IMHO.)

Do you think #1511 will come soon enough so we abandon this one, or should we bring this in as a temporary quick fix?

**Comment by santisoler** [comment]
Makes sense that including `packaging` as a dependency is a little bit overkill for this quickfix. I just replaced it by a simple snippet that compares the major and minor parts of the versions.

I think we could merge this so we have it until we start using a newer version of `pymatsolver`.

**Comment by prisae** [comment]
LGTM, thanks @santisoler!

**Pull request merged**
