### PR TITLE
ISSUE-1341: Set parent of objective functions

### LINKED ISSUE #1341: Unassigned parent attributes in Regularizations
### Describe the issue:

I believe the structure of simpeg inheritance is causing issues. I have been trying to reproduce old codes from Simpeg 0.18.0 and do not believe the argument for 'gradient_type' is the Sparse regularization is working. It looks like this is due to inheritance and setters in the current simpeg, especially with the 'parent' attribute.

It seems that a lot of these classes that rely on complex and deep inheritance have had issues and could potentially be simplified. If this is not the case, it would be nice to put in some tests to make sure that these classes have the intended behavior.

### Reproducable code example:

```python
reg = regularization.VectorAmplitude(
    mesh,
    mapping=idenMap,
    active_cells=actv,
    reference_model_in_smooth=True,
    norms=[0.0, 2.0, 2.0, 2.0],
    gradient_type="total",
)
```

### Error message:

_No response_

### Runtime information:

Not applicable

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by domfournier**
#### Summary
Assign the parent on the list of  `ComboObjectiveFunction.objfcts`, such that a child function can navigate up the tree and interact with its siblings. 

We could eventually apply the same mechanics to the `BaseObjectiveFunction`, such that the misfits can also have parental relationships, but that's beyond scope.

#### Reference issue
Closes #1341 

#### What does this implement/fix?
The parent on the objective function was never set, and prevented the Sparse amplitude to apply the `gradient_type = "total"`

### CODE REVIEW

**Comment by jcapriot** [comment]
If we do want all of the `ObjectiveFunction`s to have access to this `parent` when inside a `ComboObjectiveFunction`, you should move the validator that currently exists on `regularization.base.BaseRegularization` to the `BaseObjectiveFunction`.

I'm still not quite sold it's the way to go, but at least it would solve #1341

**Comment by domfournier** [comment]
Ok, as a compromise, I can move it down level to the WeightedLeastSquares. So at least the change is contained to the reg functions.

**Review by jcapriot — APPROVED** [review]
looks good!

**Comment by domfournier** [comment]
Thanks @jcapriot

**Pull request merged**
