### PR TITLE
Improve how path to sensitivity files are built

### PR DESCRIPTION
**Pull request by santisoler**
Create the paths to where the sensitivity arrays will be stored by the
simulations using `os.path.join` instead of concatenating strings. This makes it
safer and removes the need to remember adding a trailing slash on paths to
directories.

### CODE REVIEW

**Comment by jcapriot** [comment]
Thanks for doing this, I was running into this issue on my own re-do. Eventually I’d love to get these to accept [pathlib.PurePath](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath) objects instead.

**Comment by santisoler** [comment]
Glad to contribute! I was intending to use `pathlib.Path` to define those paths, but I'm afraid that could introduce some breaking changes, so I decided to be more conservative and just use `os.path.join()`.

BTW, is there any reason why you would choose `pathlib.PurePath` instead of `pathlib.Path` for SimPEG?

**Comment by jcapriot** [comment]
Nothing particularly different, just that `PurePath` is the parent class of the `Path` objects.

**Comment by jcapriot** [comment]
@santisoler If you can get main merged into here with the removal of `properties` that would be helpful

**Comment by santisoler** [comment]
Thanks Joe for making the default also be created with `os.path.join`. Nevertheless, it's usually advised not to define default values for parameters through function calls. Check `B008` in [bugbear's warnings](https://github.com/PyCQA/flake8-bugbear#list-of-warnings). This is another reason why would be nice to have predefined `Path` objects instead of using `os.path.join`.

**Comment by jcapriot** [comment]
Yes, I realize this issue. It should probably be set with a None argument then set with the current method.

**Pull request merged**
