### PR TITLE
Em1d single sounding

### PR DESCRIPTION
**Pull request by sgkang**
# EM1D for a single sounding

This is transferred from #1013, and removed any pieces related to the stitched inversion.

### CODE REVIEW

**Comment by sgkang** [comment]
@jcapriot: Not sure why tests are not passing. Would be great if you can take a quick look: 
https://dev.azure.com/simpeg/simpeg/_build/results?buildId=1748&view=logs&j=894b861d-556c-5901-7578-c933b75ce341&t=ed1e0f4a-533f-5064-832c-7c51df369f6b&l=12

**Comment by sgkang** [comment]
Fixed most of errors in the tests. Not sure why there is a test failing test_muinverse.py [passing on my local machine...]

**Comment by dccowan** [comment]
I was looking to expand the tests for TDEM 1D. Most notably
- having x, y and z dipole sources
- having dispersive conductivity and magnetic permeability

Since the analytic solutions in geoana aren't quite comprehensive enough yet, some of the tests cannot be written.

**Comment by jcapriot** [comment]
Should be good to go now

**Pull request merged**
