### PR TITLE
Use reviewdog to annotate PR's with black and flake8 errors.

### PR DESCRIPTION
**Pull request by jcapriot**
#### Summary
Uses reviewdog to annotate PR's with suggested changes from black, and comment on errors from flake8

#### PR Checklist
* [x] If this is a work in progress PR, set as a Draft PR
* [ ] Linted my code according to the [style guides](https://docs.simpeg.xyz/content/getting_started/contributing/code-style.html).
* [x] Added [tests](https://docs.simpeg.xyz/content/getting_started/practices.html#testing) to verify changes to the code.
* [x] Added necessary documentation to any new functions/classes following the
      expect [style](https://docs.simpeg.xyz/content/getting_started/practices.html#documentation).
* [x] Marked as ready for review (if this is was a draft PR), and converted 
      to a Pull Request
* [x] Tagged ``@simpeg/simpeg-developers`` when ready for review.

#### What does this implement/fix?
Allows for automated reviewing of PR's from reviewdog detailing the flake8 and black errors when they fail, making it much more obvious to people who have submitted PR's about why those tests are failing.

### CODE REVIEW

**Comment by jcapriot** [comment]
@santisoler Check this out!

**Comment by jcapriot** [comment]
Obviously I've currently added purposeful places for the checks to fail to look at the output, I'll make sure it triggers azure tests as well after the "failures" are fixed.

**Comment by santisoler** [comment]
Looks great! I think it could greatly improve the experience for new contributors.

Is there a way to get the github bot to use the reviewdog logo?? Would love to have it _barking_ at us for forgetting to run black haha

**Comment by jcapriot** [comment]
> Looks great! I think it could greatly improve the experience for new contributors.
> 
> Is there a way to get the github bot to use the reviewdog logo?? Would love to have it _barking_ at us for forgetting to run black haha

I don't see an option to get that setup through the pre-made actions for `flake8` and `black` unfortunately.

**Comment by jcapriot** [comment]
Perfect, looks to have properly triggered the azure pipelines runs after the style checks.

**Comment by jcapriot** [comment]
Now just need to make sure it triggers a run on this branch…

**Comment by jcapriot** [comment]
Ok, I'm happy with how this is setup now.
It does re-run the black/flake8 tests on azure, mostly because we still only want the tests to run if those things pass. Essentially the GitHub-actions workflow is only used to post review comments detailing for users about the specific flake8 error, or how to change the formatting to satisfy black.

**Pull request merged**
