### PR TITLE
Add Ying and Williams to AUTHORS.rst

### PR DESCRIPTION
**Pull request by santisoler**
#### Summary

Add @ghwilliams @YingHuuu to `AUTHORS.rst`.

#### PR Checklist
* [ ] If this is a work in progress PR, set as a Draft PR
* [ ] Linted my code according to the [style guides](https://docs.simpeg.xyz/content/getting_started/contributing/code-style.html).
* [ ] Added [tests](https://docs.simpeg.xyz/content/getting_started/practices.html#testing) to verify changes to the code.
* [ ] Added necessary documentation to any new functions/classes following the
      expect [style](https://docs.simpeg.xyz/content/getting_started/practices.html#documentation).
* [ ] Marked as ready for review (if this is was a draft PR), and converted
      to a Pull Request
* [ ] Tagged ``@simpeg/simpeg-developers`` when ready for review.

### CODE REVIEW

**Comment by santisoler** [comment]
@YingHuuu @ghwilliams, would you comment here consenting to add your name to the `AUTHORS.rst` file?

**Comment by YingHuuu** [comment]
Sure. Thanks, Santi~

**Comment by ghwilliams** [comment]
Yes, it is an honor to be in this file!!

**Review by jcapriot — APPROVED** [review]
LGTM Thanks for your contributions!

**Pull request merged**
