### PR TITLE
Tutorial notebook FDEM: Only calculate response for a single frequency

### PR DESCRIPTION
**Pull request by williamjsdavis**
#### Summary

Updates the tutorial notebook for frequency-domain electromagnetics tutorial notebook "3D Forward Simulation on a Tree Mesh," to correctly only calculate response for a single frequency.

#### PR Checklist
* [x] If this is a work in progress PR, set as a Draft PR
* [x] Linted my code according to the [style guides](https://docs.simpeg.xyz/latest/content/getting_started/contributing/code-style.html).
* [x] Added [tests](https://docs.simpeg.xyz/latest/content/getting_started/contributing/testing.html) to verify changes to the code.
* [x] Added necessary documentation to any new functions/classes following the
      expect [style](https://docs.simpeg.xyz/latest/content/getting_started/contributing/documentation.html).
* [x] Marked as ready for review (if this is was a draft PR), and converted 
      to a Pull Request
* [x] Tagged ``@simpeg/simpeg-developers`` when ready for review.

#### Reference issue

None.

#### What does this implement/fix?

This PR makes a small change to the frequency-domain electromagnetics tutorial notebook, for the "3D Forward Simulation on a Tree Mesh" example, i.e.:

https://docs.simpeg.xyz/latest/content/tutorials/07-fdem/plot_fwd_3_fem_3d.html

The notebook says:

> To save time, we will only compute the response for a single frequency.

https://github.com/simpeg/simpeg/blob/50b79e287227e965cd3ca22ff297615e74d50a28/tutorials/07-fdem/plot_fwd_3_fem_3d.py#L66-L68

However, I noticed that responses were actually being calculated for 3 frequencies:

https://github.com/simpeg/simpeg/blob/50b79e287227e965cd3ca22ff297615e74d50a28/tutorials/07-fdem/plot_fwd_3_fem_3d.py#L72

My change alters the frequency line to specify the intended single frequency. This removes unnecessary computation (on my laptop, it speeds up the execution of the notebook x3).

https://github.com/williamjsdavis/simpeg/blob/dd6c79a1ddc578e8342bca72d91d06e177d8be2a/tutorials/07-fdem/plot_fwd_3_fem_3d.py#L72

I also change the definition of axes titles of the final plot, from:

https://github.com/simpeg/simpeg/blob/50b79e287227e965cd3ca22ff297615e74d50a28/tutorials/07-fdem/plot_fwd_3_fem_3d.py#L260

https://github.com/simpeg/simpeg/blob/50b79e287227e965cd3ca22ff297615e74d50a28/tutorials/07-fdem/plot_fwd_3_fem_3d.py#L280

... so now the titles display the referenced frequency, in case the user changes the defined frequency back on line 72.

https://github.com/williamjsdavis/simpeg/blob/dd6c79a1ddc578e8342bca72d91d06e177d8be2a/tutorials/07-fdem/plot_fwd_3_fem_3d.py#L260

https://github.com/williamjsdavis/simpeg/blob/dd6c79a1ddc578e8342bca72d91d06e177d8be2a/tutorials/07-fdem/plot_fwd_3_fem_3d.py#L280

#### Additional information

None

### CODE REVIEW

**Comment by williamjsdavis** [comment]
@simpeg/simpeg-developers @santisoler this PR is ready for review

**Comment by santisoler** [comment]
Hi @williamjsdavis. Thanks for opening this PR. I really appreciate your contribution.

In the past year we started moving the tutorials to their own repository: https://github.com/simpeg/user-tutorials. Can I ask you to open a PR in that repo to apply the same changes? I know that @dccowan modify them while creating the new repo, so I'm not sure if the same tutorial is still using a single frequency or not.

Sorry for the inconvenience and for the lack of clarity on the maintenance status of the tutorials in this repo. We are planning to finally remove them from here (see #1555 as reference).

**Comment by williamjsdavis** [comment]
Ah no problem, I didn't know that tutorials repo even existed! I'll review the that repo's corresponding tutorial and see if any corrections need to be made, and if so I'll open a PR there. Feel free to delete this PR

**Comment by santisoler** [comment]
Thanks @williamjsdavis! I'm closing this issue.

I'm working now in updating the tutorials to work with the latest version of SimPEG (v0.23.0), so expect a few changes coming in soon.

**Pull request closed without merging**
