### PR TITLE
Mesh/tree

### PR DESCRIPTION
**Pull request by rowanc1**
- Working octree/quadtree implementation (operators, refining, averaging, corsening, O(h) interpolation)
- Updates to setup.py
- Commiting the compiled C codes.

### CODE REVIEW

**Comment by rowanc1** [comment]
Our Dev branch seems to be out of date (so I am pulling into master and will rename and branch off of dev...).

**Comment by lheagy** [comment]
14000+ lines of code! Looks good :)

**Comment by rowanc1** [comment]
Did you read it all?!?

**Comment by lheagy** [comment]
every line. with care

**Pull request merged**
